### ISSUE TITLE
AVFormatContext.openInput crash

### ISSUE THREAD

**Issue by shnhrrsn** [sunlubo/SwiftFFmpeg#11]
I'm getting a crash when calling `AVFormatContext.openInput` with an unsupported file (missing codec in my case):

<img width="1272" alt="screen shot 2018-12-31 at 11 52 32 am" src="https://user-images.githubusercontent.com/42901/50564400-94d33780-0cf2-11e9-8f14-4e0d8d672665.png">

**Comment by sunlubo** [comment]
It has been fixed on master.
