### ISSUE TITLE
AVCodec findDecoder/findEncoder failure pattern

### ISSUE THREAD

**Issue by shnhrrsn** [sunlubo/SwiftFFmpeg#12]
The `findDecoder*`/`findEncoder*` methods in `AVCodec` return nil on failure rather than throwing an error, is there any reason this is the case?

I’m still new to using this, but I’m finding myself having to do to something like this a lot:

```swift
guard let codec = AVCodec.findDecoderById(.H264) else {
  throw /* (custom error) */
}
```

Being able to do something like this feels like it would be much more consistent with the rest of the API:

```swift
let codec = try AVCodec.findDecoderById(.H264)
```

**Comment by sunlubo** [comment]
The reason is the absence of the codec does not mean an error for the framework, so I prefer to use Optional.
