### ISSUE TITLE
Missing required module 'CFFmpeg'

### ISSUE THREAD

**Issue by DogerRua** [sunlubo/SwiftFFmpeg#18]
This error occurs when I import 'swiftffmpeg'. Please answer it.

**Comment by sunlubo** [comment]
Please confirm that your system has FFmpeg installed.

**Comment by DogerRua** [comment]
Ffmpeg has been installed, but cffmpeg file is found to be empty when using package integration

**Comment by sunlubo** [comment]
<img width="1434" alt="截屏2019-10-22下午7 19 42" src="https://user-images.githubusercontent.com/5688074/67280964-f0301980-f500-11e9-8fd6-d65614c30f7e.png">
Is your project like this?

**Comment by DogerRua** [comment]
Yes, but I configured it in IOS environment

**Comment by DogerRua** [comment]
Now I'm learning about your library from the iosdemo you published. I hope you can give me a more detailed demo of using the library you developed.

**Comment by DogerRua** [comment]
Thank you very much.

**Comment by sunlubo** [comment]
Which type of example do you want?

**Comment by DogerRua** [comment]
I want to use your library to add filters to videos and things like that.

**Comment by sunlubo** [comment]
For video filters, you can refer to this [example](https://github.com/sunlubo/SwiftFFmpeg/blob/master/Sources/Examples/filtering_video.swift).

**Comment by DogerRua** [comment]
Thank you
