### ISSUE TITLE
Convert AVFrame to image

### ISSUE THREAD

**Issue by teaglin** [sunlubo/SwiftFFmpeg#2]
Do you have any examples you could share of converting an avframe to raw rgb or maybe even a png/jpeg?

**Comment by sunlubo** [comment]
See https://gist.github.com/sunlubo/0de1dcf0bbb3eca0e09704e2b71e92ba

**Comment by teaglin** [comment]
Thank you so much. Really appreciate it.!

**Comment by smhk** [comment]
This is magic, but what about if you just want a UIImage?

So it's going to be something like

**Comment by teaglin** [comment]
This is what I used https://gist.github.com/teaglin/3eeee612261389929f283fe7e305a510 – based on sunlubo's gist it returns the raw rgb24 as Data.

**Comment by smhk** [comment]
howdy @teaglin , gotchya,

say I think on line 50

https://gist.github.com/teaglin/3eeee612261389929f283fe7e305a510

actually those are our Int not Int32 ?

**Comment by teaglin** [comment]
That sounds correct. I forgot to mention I slightly modified some of the original code and added new functionality to get it to work on Linux and work with other code. I don't remember exactly why that particular piece was changed to use Int32. But overall that gist should work.

**Comment by smhk** [comment]
gotchya, and thanks a million

I'm having a shitty problem on iOS where, at line 9  swsCtx = SwsContext( 

on the iOS side I just get 

"[swscaler @ 0x10a820000] No accelerated colorspace conversion found from yuv420p to rgb24."

I'd be happy for it to just use a slow scaler as it's only for debugging  :)

thanks again ...

**Comment by teaglin** [comment]
I guess FFMpeg for iOS does not support that conversion? You could just keep it at yuv420p then use the Accelerate iOS framework to convert to RGB

**Comment by smhk** [comment]
howdy @teaglin -you know, I just learned after searching for ages that is only a WARNING, 

it appears to be the case that ffmpeg then simply goes ahead and does the conversion using the normal CPU code; it's just a warning letting you know it's not using the GPU.

It seems.

(So, my "it comes out blank!" problem is unrelated!)

**Comment by smhk** [comment]
Ah, for anyone using this critical script

https://gist.github.com/sunlubo/0de1dcf0bbb3eca0e09704e2b71e92ba

there's a simple thing, at 

`let fmtCtx = try AVFormatContext(format: nil, filename: url)`

the filename can't be say "test"

the filename has to be "test.png", **you have to have an extension**

this held me up for an hour  :)

so on iOS you will have

```
let pp =
  NSSearchPathForDirectoriesInDomains(
    .documentDirectory,
    .userDomainMask,
    true).first!
    + "/test.png"
try savePNG(frame, to: pp)
```

**Comment by Sajjon** [comment]
These gists are quite old and does not work with latest version of `SwiftFFmpeg`, does anyone have an updated version?

(My idea is to create a .mov using `AVAssetWriter` and `AVAssetWriterInputPixelBufferAdaptor` and append each AVFrame to the pixeulBufferAdaptor, which requires an `CIImage` or `CGImage`.)
