### ISSUE TITLE
Guidance: Extract Audio from video

### ISSUE THREAD

**Issue by pankajsoni19** [sunlubo/SwiftFFmpeg#24]
I have used both swift and ffmpeg. I had a trouble understand the ffmpeg examples, could you guide me. my use case is:

I have video mp4 data thats uploaded to myserver in Swift `Data` and I want to extract out only audio in mp3 format.

**Comment by sunlubo** [comment]
You can refer to [avio_reading](https://github.com/sunlubo/SwiftFFmpeg/blob/master/Sources/Examples/avio_reading.swift) and [split_stream](https://github.com/sunlubo/SwiftFFmpeg/blob/master/Sources/Examples/split_stream.swift)
