### ISSUE TITLE
Use for converting file types?

### ISSUE THREAD

**Issue by loldi** [sunlubo/SwiftFFmpeg#31]
Is it feasible to use this library to convert video files from the users camera roll?  Trying to convert .MOV -> .MP4 using the native Swift libraries, but they do something weird to the output file that I'm having trouble using.  Hoping to basically emulate:

`ffmpeg -i my-video.mov -vcodec h264 -acodec mp2 my-video.mp4`

With this library, but unsure.

**Comment by sunlubo** [comment]
You can refer to this [demo](https://github.com/sunlubo/SwiftFFmpeg/blob/master/Sources/Examples/remuxing.swift).
