### ISSUE TITLE
Expose `avformat_seek_file`

### ISSUE THREAD

**Issue by AlaaAlHallaq** [sunlubo/SwiftFFmpeg#33]
`AVFormatContext.seekFrame` relay on `av_seek_frame` which for some reasons  fails of seeking with `Operation not permitted` error code, but using `avformat_seek_file` after exposing some internals of your wrapper swift classes, it worked just fine on multiple samples.

so I ask you to expose as much ffmpeg internal api as possible from the underlying `ffmpeg` c library, also accessing pointers to the underlying ffmpeg types would be helpful to work on the internals without the need to use a fork of your project.

one more thing if you added a wrapper method to seek to a specific time (in seconds) as a helper function, without the need to convert from timestamp to pts, it would be very helpful.
 
Regards

**Comment by sunlubo** [comment]
You can list all the api you need, I can add them later.
