### ISSUE TITLE
No such module 'SwiftFFmpeg' in Xcode 11.5 on Catalina (works in Xcode 11.3.1 on Mojave)

### ISSUE THREAD

**Issue by maculateConception** [sunlubo/SwiftFFmpeg#40]
Hello, I have your package imported into my Xcode v11.5 on macOS Catalina using the git repo URL. It shows up properly under "Swift Package Dependencies" in the navigation pane and also under Project settings, but refuses to resolve the dependency so I always get "No such module 'SwiftFFmpeg'". This behavior is only in Xcode v11.5 on macOS Catalina.

It works perfectly fine in Xcode v11.3.1 on macOS Mojave.

Any ideas why ? I would appreciate some help with this because I really am clueless. I have tried removing/re-adding the package many times, cleaning, re-building, deleting DerivedData folder, etc. Just cannot get it to work.

Thank you.

**Comment by sunlubo** [comment]
Can you share a reproducible project?

**Comment by maculateConception** [comment]
> Can you share a reproducible project?

Yup, please find attached a zip file containing the .xcodeproj and all relevant sources.

What's funny is ... I tried running one last time before replying to you. This time, the error has changed to "Framework not found: -framework". I checked the "Other linker flags" in "Build Settings" but those were empty. So that's strange.

The exact same project works like a charm on macOS Mojave.

BTW, great work on this project ! I had been looking for something like this for the last couple of years. I have learned quite a bit from your code.

[Aural-FFMpeg.zip](https://github.com/sunlubo/SwiftFFmpeg/files/4981450/Aural-FFMpeg.zip)

**Comment by sunlubo** [comment]
Hi, the attached project works fine on my mac.

<img width="1056" alt="截屏2020-07-27 下午7 18 49" src="https://user-images.githubusercontent.com/5688074/88536249-12ca0280-d03e-11ea-8b9e-863ee0ae54a9.png">

**Comment by maculateConception** [comment]
Hmm, I see that you are using Xcode 11.6. Maybe I will try upgrading to 11.6 and see if that helps.

Thanks for trying this out and letting me know.
