### ISSUE TITLE
When building for Mac, can't find auto-linked libraries?

### ISSUE THREAD

**Issue by smhk** [sunlubo/SwiftFFmpeg#5]
Using brew install ffmpeg, ffmpeg is running fine on my Mac,

$ ls -l /usr/local/bin/ | grep ffm
-rwxr-xr-x  1 jpm   admin  20686092 Dec 16 13:31 ffmpeg

However when I swift build:

$ swift build
Linking ./.build/x86_64-apple-macosx10.10/debug/SwiftFFmpegDemo
ld: warning: Could not find auto-linked library 'swresample'
ld: warning: Could not find auto-linked library 'avutil'
ld: warning: Could not find auto-linked library 'avfilter'
ld: warning: Could not find auto-linked library 'avcodec'
ld: warning: Could not find auto-linked library 'avformat'
ld: warning: Could not find auto-linked library 'swscale'
Undefined symbols for architecture x86_64:
  "_av_buffer_alloc", referenced from:
      _$S11SwiftFFmpeg8AVBufferC4sizeACSgSi_tcfc in AVBuffer.swift.o
(and many Undefined symbols errors like that)

What to do??  thanks!

**Comment by smhk** [comment]
Thank you so much, where is the tip jar please?

> $ swift --version
> Apple Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)
> Target: x86_64-apple-darwin18.2.0

and

> $ brew info ffmpeg
> ffmpeg: stable 4.1 (bottled), HEAD
> Play, record, convert, and stream audio and video https://ffmpeg.org/
> /usr/local/Cellar/ffmpeg/4.1 (282 files, 55.4MB)
>   Poured from bottle on 2018-12-17 at 08:38:36
> From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ffmpeg.rb
> ==> Dependencies
> Build: nasm ✘, pkg-config ✔, texi2html ✘
> Required: lame ✔, libvorbis ✔, libvpx ✔, opus ✔, sdl2 ✔, snappy ✔, theora ✔, x264 ✔, x265 ✔, xvid ✔, xz ✔
> Optional: (etc...)

**Comment by sunlubo** [comment]
Do you have ffmpeg's pkgconfig file on `/usr/local/lib/pkgconfig` ? 

```
sun$ cd /usr/local/lib/pkgconfig
sun$ ls -al
lrwxr-xr-x    1 sun  admin    51 11 11 08:00 libavcodec.pc -> ../../Cellar/ffmpeg/4.1/lib/pkgconfig/libavcodec.pc
lrwxr-xr-x    1 sun  admin    52 11 11 08:00 libavdevice.pc -> ../../Cellar/ffmpeg/4.1/lib/pkgconfig/libavdevice.pc
lrwxr-xr-x    1 sun  admin    52 11 11 08:00 libavfilter.pc -> ../../Cellar/ffmpeg/4.1/lib/pkgconfig/libavfilter.pc
lrwxr-xr-x    1 sun  admin    52 11 11 08:00 libavformat.pc -> ../../Cellar/ffmpeg/4.1/lib/pkgconfig/libavformat.pc
lrwxr-xr-x    1 sun  admin    54 11 11 08:00 libavresample.pc -> ../../Cellar/ffmpeg/4.1/lib/pkgconfig/libavresample.pc
lrwxr-xr-x    1 sun  admin    50 11 11 08:00 libavutil.pc -> ../../Cellar/ffmpeg/4.1/lib/pkgconfig/libavutil.pc
```

**Comment by smhk** [comment]
Thanks again,

1) they are there

2) libavresample.pc is missing; however there is a "libswresample.pc"

3) in my case they are **files, not links**

```
fattie$ cd /usr/local/lib/pkgconfig
fattie$ ls -la libav*
-rw-r--r--  1 fattie  admin  485 Dec 16 13:31 libavcodec.pc
-rw-r--r--  1 fattie  admin  555 Dec 16 13:31 libavdevice.pc
-rw-r--r--  1 fattie  admin  499 Dec 16 13:31 libavfilter.pc
-rw-r--r--  1 fattie  admin  426 Dec 16 13:31 libavformat.pc
-rw-r--r--  1 fattie  admin  401 Dec 16 13:31 libavutil.pc
```

4) perhaps a problem with paths in the Xcode project ??

![image](https://cdn.pbrd.co/images/HTeTYnp.png)

5) notice it is complaining about architecture x86_64 in particular?

here's the errors...

![errors](https://cdn.pbrd.co/images/HTeV8Ha.png)

**Comment by sunlubo** [comment]
Hi, I can't reproduce this problem on my mac😓. Currently, you can manually specify linker parameters to build this demo.
`swift build -Xlinker -L/usr/local/Cellar/ffmpeg/4.1_1/lib`

**Comment by smhk** [comment]
Understood!  Sorry to bring this to your attention but today:


$ swift build -Xlinker -L/usr/local/Cellar/ffmpeg/4.1_1/lib
Compile Swift Module 'SwiftFFmpeg' (24 sources)
/Users/jpm/Desktop/SwiftFFmpeg-master/Sources/SwiftFFmpeg/AVOptions.swift:107:55: error: use of unresolved identifier 'AV_OPT_FLAG_DEPRECATED'
        public static let deprecated = Flag(rawValue: AV_OPT_FLAG_DEPRECATED)
                                                      ^~~~~~~~~~~~~~~~~~~~~~
error: terminated(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/fattie/Desktop/SwiftFFmpeg-master/.build/debug.yaml main output:

**Comment by sunlubo** [comment]
From the information you provided before, your ffmpeg version is 4.1. So, maybe you should use 
`swift build -Xlinker -L/usr/local/Cellar/ffmpeg/4.1/lib`.

**Comment by yoiang** [comment]
What is the recommended version of **FFMPEG**? I have 4.0 and `swift build -Xlinker -L/usr/local/Cellar/ffmpeg/4.0/lib` results in similar

```sh
/.../.build/checkouts/SwiftFFmpeg/Sources/SwiftFFmpeg/AVBitStreamFilter.swift:148:9: error: use of unresolved identifier 'av_bsf_flush'
        av_bsf_flush(cContextPtr)
        ^~~~~~~~~~~~
CFFmpeg.av_bsf_alloc:1:13: note: did you mean 'av_bsf_alloc'?
public func av_bsf_alloc(_ filter: UnsafePointer<AVBitStreamFilter>!, _ ctx: UnsafeMutablePointer<UnsafeMutablePointer<AVBSFContext>?>!) -> Int32
            ^
CFFmpeg.av_bsf_free:1:13: note: did you mean 'av_bsf_free'?
public func av_bsf_free(_ ctx: UnsafeMutablePointer<UnsafeMutablePointer<AVBSFContext>?>!)
            ^
CFFmpeg.avio_flush:1:13: note: did you mean 'avio_flush'?
public func avio_flush(_ s: UnsafeMutablePointer<AVIOContext>!)
            ^
/.../.build/checkouts/SwiftFFmpeg/Sources/SwiftFFmpeg/AVOptions.swift:177:55: error: use of unresolved identifier 'AV_OPT_FLAG_DEPRECATED'
        public static let deprecated = Flag(rawValue: AV_OPT_FLAG_DEPRECATED)
                                                      ^~~~~~~~~~~~~~~~~~~~~~

```

**Comment by sunlubo** [comment]
`av_bsf_flush` was added in ffmpeg 4.1, so you should use this version.
see [APIChanges](https://github.com/FFmpeg/FFmpeg/blob/master/doc/APIchanges) .

**Comment by sunlubo** [comment]
#41
