### ISSUE TITLE
AVStream – display_aspect_ratio removed

### ISSUE THREAD

**Issue by teaglin** [sunlubo/SwiftFFmpeg#50]
In the Oct 20th update of FFMPEG they removed display_aspect_ratio in AVStream. This causes an error with building. Removing it in SwiftFFMPEG resolves the issue.

https://www.mail-archive.com/ffmpeg-cvslog@ffmpeg.org/msg45630.html

**Comment by sunlubo** [comment]
thanks

**Comment by sunlubo** [comment]
Fixed.
