### ISSUE TITLE
Foundation.Data from AVFrame’s `data` property

### ISSUE THREAD

**Issue by Sajjon** [sunlubo/SwiftFFmpeg#53]
Im not great at pointer syntax, how can I convert an AVFrame instance data into Swift Foundation `Data`

(End goal is to convert a Bink Video to an AVPlayer playable item, Im trying each AVFrame => Data => CIImage => CVPixelBuffer => append to AVAssetWriteeInput (AVAssetWriterInputPixelBufferAdaptor))

**Comment by sunlubo** [comment]
video data is stored in AVFrame.data

**Comment by Sajjon** [comment]
Yes, that's what I said, and its type is `UnsafeMutableBufferPointer<UnsafeMutablePointer<UInt8>?>`

And Im asking how I can convert that type into `Data`?

**Comment by Sajjon** [comment]
@sunlubo Or rather, how can I create an `CIImage` or `CGImage` from an `AVFrame`? :)

**Comment by Sajjon** [comment]
But it is outdated and still references the (now updated) and hard to use type `data`,  hmm...

**Comment by gregcotten** [comment]
To initialize without copying (you must hold onto the AVFrame and make sure it's not unref'd until you're done with Data!

```swift
let data = Data(bytesNoCopy: .init(frame.data[0]!), count: Int(frame.linesize[0]), deallocator: .none)
```

An untested method to have the Data safely deallocate the frame when no longer needed:

```swift
let data = Data(bytesNoCopy: .init(frame.data[0]!), count: Int(frame.linesize[0]), deallocator: .custom({ _, bytes in
                        assert(bytes == Int(frame.frame.linesize[0]))
                        frame.unref()
                    }))
```

To initialize with Data by copying:

```swift
Data(buffer: .init(start: frame.data[0], count: Int(frame.linesize[0])))
```

Remember if you are sampling planar frame data (planar audio channels or YCbCr data), you'll need to get each valid plane (I was just using an index of 0)

**Comment by Sajjon** [comment]
@gregcotten thx a lot! Hmm im a little bit over my head here, I wanna play a BINK (bik files) video on macOS and Im able to read frame data using (Swift)FFmpeg. And I thought I would be able to save each individual frame as an CIImage and write usinf AVAsserWriter and that way somehow save the whole series of frames as a .MOV or similar movie that I can play with AVPlayer.

I tried using just index 0, but saw in debugger that index 1 and 2 of frame.data contained bytes, I tried concatenating output of your sample for each index respectively and use that as input to CIImage initializer, but it results in nil...

Any idea?

**Comment by Sajjon** [comment]
Thx for the help @gregcotten ! maybe we ought to Swiftify those properties and change to [Data] instead of `UnsafeMutableBufferPointer<UnsafeMutablePointer<UInt8>?>` ?

**Comment by chris-mds** [comment]
Hi @Sajjon ,

did you have a working code snippet of your function?
I modified it like the following code, but still no successful conversion to the image property.
Even better would be a conversion function to `CMSampleBuffer`
Maybe some ideas?

```
var dataSingleFrame = Data()
for (_, maybeFrameData) in frame.buf.enumerated() {
  guard let frameData = maybeFrameData else {
      break
  }
  let singleFramePartData = Data(bytesNoCopy: .init(frameData.data), count: frameData.size, deallocator: .none)
  dataSingleFrame.append(contentsOf: singleFramePartData)
}


guard let ciImage = CIImage(data: dataSingleFrame) else {
  print("Failed to create CI image from data")
  continue
}
```
