### ISSUE TITLE
xcode 14.2 build failed. With error  Cannot find 'AV_CH_FRONT_LEFT' in scope

### ISSUE THREAD

**Issue by kmitj** [sunlubo/SwiftFFmpeg#60]
![Screen Shot 2023-02-27 at 13 01 04](https://user-images.githubusercontent.com/26257629/221507652-e93766bc-8360-43a1-a8f0-7c400baf2598.png)

**Comment by jaceklapinski** [comment]
Same problem:

ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers

How to resolve this ?

**Comment by sunlubo** [comment]
I will upgrade to FFmepg 6.0 later.

**Comment by sunlubo** [comment]
> Ok, thx!
> 
> But current source code should works with ffmpeg version 5.1.3 ?

**Comment by sunlubo** [comment]
The main branch has been upgraded to FFmpeg 6.0.
